config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  root 'nl#home'
  get 'nl/about'
  get 'nl/sectoren'
  get 'nl/legal'
  get 'nl/prijs'
  get 'nl/werkwijze'
  get 'nl/diensten'
  get 'nl/contact'
  get 'nl/pentest'
  get 'nl/webapp'
  get 'nl/api'
  get 'nl/awspen'
  get 'nl/cloud'
  get 'nl/expert'
  get 'nl/mobile'
  get 'nl/pentest'
  get 'nl/phishing'
  get 'nl/redteam'
  get 'nl/socialeng'
  get 'nl/wireless'
  get 'nl/workshops'
                    
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :author)
    end
end

app/controllers/nl_controller.rb
class NlController < ApplicationController
  def home
  end

  def about
  end
  
  def sectoren
  end

  def legal
  end

  def prijs
  end

  def werkwijze
  end

  def diensten
  end
  
  def contact
  end
  
  def pentest
  end
  
  def webapp
  end
  
    def api
  end
  
    def awspen
  end
  
    def cloud
  end
  
    def expert
  end
  
    def mobile
  end
  
    def redteam
  end
  
    def socialeng
  end
  
    def wireless
  end
  
    def workshops
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/nl_helper.rb
module NlHelper
end

app/views/blogs/_blog.html.erb
<div class="flex flex-col overflow-hidden rounded-lg shadow-lg font-Prompt uppercase" id="<%= dom_id blog %>">
        <div class="flex flex-1 flex-col justify-between bg-white p-6">
          <div class="flex-1">
            <a href="#" class="mt-2 block">
              <p class="text-lg font-semibold text-gray-500 block"><%= blog.title %></p>
              <p class="mt-3 text-base text-gray-500"><%= blog.body.truncate(50) %></p>
              <%= link_to "Lees meer", blog, class: " inline-block font-medium" %>
            </a>
          </div>
          <div class="mt-6 flex items-center">
            <div class="flex-shrink-0">
              <a href="#">
                <span class="sr-only"><%= blog.author %></span>
                <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
              </a>
            </div>
            <div class="ml-3">
              <p class="text-sm font-medium text-gray-900">
                <a href="#" class="hover:underline"><%= blog.author %></a><br>
                <%= blog.created_at %>
              </p>
            </div>
          </div>
        </div>
      </div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, class: "contents") do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author %>
    <%= form.text_field :author, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing blog</h1>

  <%= render "form", blog: @blog %>

  <%= link_to "Show this blog", @blog, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to blogs", blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/blogs/index.html.erb
<div class="w-full bg-white">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

    <div class="text-center font-Prompt uppercase p-10">
      <h2 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-5xl">PUBLICATIES EN ONDERZOEKEN</h2>
      <p class="mx-auto mt-3 max-w-2xl text-xl text-gray-500 sm:mt-4">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa libero labore natus atque, ducimus sed.</p>
    </div>

    <div class="relative mx-auto max-w-7xl">
    <div class="mx-auto mt-12 grid max-w-lg gap-5 lg:max-w-none lg:grid-cols-3">
    <%= render @blogs %>
    </div>
    </div>
    <%= link_to 'New blog', new_blog_path, class: "text-black block font-medium font-Prompt uppercase" %>
</div>

app/views/blogs/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New blog</h1>

  <%= render "form", blog: @blog %>

  <%= link_to 'Back to blogs', blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/blogs/show.html.erb
<div class="mx-auto bg-white w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

        <div class="text-center font-Prompt uppercase p-10">
          <h2 class="text-xl font-bold tracking-tight text-gray-400"><%= @blog.created_at %></h2>
      <h2 class="text-2xl font-bold tracking-tight text-gray-900 sm:text-5xl"><%= @blog.title %></h2>
    </div>
    <div>
      <p class="text-2xl max-w-3xl">
        <%= @blog.body %>
      </p>
    </div>

    <%= link_to 'Edit this blog', edit_blog_path(@blog), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this blog', blog_path(@blog), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to blogs', blogs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samoray</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-[#BA9C7A]">
      
    <main class="">
      <%= yield %>
    </main>
    </div>
  </body>
</html>

app/views/nl/api.html.erb
<div data-tf-sidetab="vSahqHZQ" data-tf-button-color="#FBBF24" data-tf-button-text="GRATIS AFSPRAAK BOEKEN" style="all:unset;"></div><script src="//embed.typeform.com/next/embed.js"></script>




<div class="relative overflow-hidden bg-black py-16">
  <div class="hidden lg:absolute lg:inset-y-0 lg:block lg:h-full lg:w-full lg:[overflow-anchor:none]">
    <div class="relative mx-auto h-full max-w-prose text-lg" aria-hidden="true">

    </div>
  </div>
  <div class="relative px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-prose text-lg ">
      <h1>
        <span class="bg-white p-10 block text-center text-lg font-semibold font-Prompt text-black uppercase">Penetratietesten identificeren en exploiteren de beveiligingsproblemen van uw organisatie door middel van een systematisch testproces dat is gericht op uw netwerken, applicaties, fysieke faciliteiten en menselijke activa.</span>
        <span class="mt-2 block text-center text-3xl font-bold leading-8 tracking-tight font-Prompt text-white uppercase sm:text-7xl">Penetratietest Diensten</span>
      </h1>
      <hr>
    </div>
    <div class="mx-auto max-w-prose mx-auto mt-6 font-Prompt text-white uppercase">
      <h1>
          Wat zijn de soorten penetratietesten?
      </h1>
            <h2>
          Diensten voor netwerkpenetratietesten
      </h2>
            <p>
          Het is van cruciaal belang om over een sterke netwerkbeveiliging te beschikken. Door interne penetratietests op het netwerk en externe netwerkpenetratietests op uw infrastructuur uit te voeren, kunt u eventuele gebreken op netwerk- en systeemniveau ontdekken die tot kwetsbaarheden kunnen leiden. Dit omvat, maar is niet beperkt tot, verkeerde configuraties, kwetsbaarheden in draadloze netwerken, frauduleuze services, productspecifieke kwetsbaarheden, zwakke wachtwoorden en protocollen. U ziet precies wat er zou gebeuren als een kwaadwillende een beveiligingsprobleem zou ontdekken en uw bestaande netwerkbeveiliging zou doorbreken.
      </p>
                  <h2>
        Testdiensten voor cloudpenetratie
      </h2>
            <p>
          When networks and web applications are in the cloud, it is still essential to ensure their security. This would generally include a penetration test. While testing in the cloud is very similar to a hosted network or application penetration test, some additional testing is specific to each environment. Both Microsoft Azure and Amazon Web Services (AWS) provide powerful tools to manage configurations and security. If the configurations are not done correctly, there could be unexpected vulnerabilities in the environment.
      </p>
                  <h2>
          Diensten voor het testen van pennen voor webtoepassingen
      </h2>
            <p>
          Gerichte penetratietests van webapplicaties helpen u bij het ontdekken van tekortkomingen in de applicatielaag en verkeerde configuraties, zoals cross-site request vervalsing, injectiefouten, zwak sessiebeheer, cross-site scripting, onveilige directe objectreferenties en meer. Onze pentesters passen applicatiebeveiligingstests toe om misbruikbare kwetsbaarheden in uw web-apps op te sporen voordat cybercriminelen dat doen.
</p>
<p>
    Tegenwoordig is het testen van de beveiliging van webapplicaties noodzakelijk, maar het is vaak moeilijk om het goed te doen als je jongleert met vele andere aspecten van ontwikkeling. Onze applicatiebeveiligingstesters zijn ervaren softwareontwikkelaars en begrijpen applicaties zowel vanuit het ontwikkelingsperspectief als vanuit het oogpunt van beveiliging. Ongeveer 80% van onze applicatietesten is handmatige pentesting, terwijl de resterende 20% wordt uitgevoerd met behulp van geautomatiseerde testmethoden. Wij helpen u uw gevoelige gegevens te beschermen.
      </p>
                  <h2>
          Testdiensten voor draadloze pennen
      </h2>
            <p>
          Een draadloze kwetsbaarheidsbeoordeling kan u vertellen welke Wi-Fi-apparaten in uw omgeving aanwezig zijn en of uw omgeving in overeenstemming is met de brancheconformiteit en best practices. Met meer diepgaande tests kan een beoordeling ook de draadloze infrastructuur, prestaties en beveiliging van het (de) bestaande draadloze netwerk(en) van een organisatie onderzoeken. Als u dit doet, krijgt u een volledig inzicht in de sterke en zwakke punten van de omgeving. Eenmaal gewapend met die informatie, kunnen intelligente beslissingen worden genomen om zwakke prestatiegebieden te verbeteren.
      </p>
                  <h2>
          Penetratietestdiensten voor mobiele applicaties
      </h2>
            <p>
          Mobiel is een essentieel onderdeel geworden van elke bedrijfsstrategie. Het is niet langer een noviteit maar een noodzaak. Slechte actoren weten dit en zullen meedogenloos manieren zoeken om zowel iOS- als Android-systemen te infiltreren om zwakke punten in de beveiliging aan het licht te brengen. Onze penetratietesters gaan dieper in op de besturingssystemen van uw organisatie en de bijbehorende apps. Vervolgens simuleren ze aanvallen uit de echte wereld (ethisch hacken) om eventuele risico's te ontdekken die verband houden met het mobiele gebruik van uw organisatie.
      </p>
                  <h2>
          Testdiensten voor fysieke penetratietesten
      </h2>
            <p>
          U kunt eersteklas fysieke beveiligingsmaatregelen installeren, zoals sloten, sensoren, smartcards en camera's. Toch zullen criminelen altijd proberen u een stap voor te blijven om ongeautoriseerde toegang te krijgen. Cybercriminelen kunnen uw bedrijf grote risico's opleveren, en dat is waar fysieke pentesten van pas komen. Fysieke penetratietesters zullen naar alle aspecten van uw fysieke faciliteit kijken, van binnen en van buiten, om er zeker van te zijn dat uw processen en fysieke beveiligingen een cyberaanval en de criminelen die toegang proberen te krijgen tot uw gebouw of de mensen die erin werken.
      </p>
        <h1>
          Klaar om uw beveiliging te verbeteren?
      </h1>
      <p>
          We kunnen u helpen te zien hoe goed de beveiligingsstrategie van uw organisatie presteert. Ontdek wat ons onderscheidt van andere aanbieders van penetratietestdiensten. Plan vandaag nog uw gratis virtuele vergadering met een expert op 016 41 42 88.
      </p>
      <div class="bg-white p-10 text-black">
          
            <h1>
          Veelgestelde vragen
      </h1>
      <h2>
          Top 5 Pentest technieken?
      </h2>
            <p>
          Er zijn veel verschillende soorten penetratietesten, waaronder maar niet beperkt tot;
- Externe netwerkpenetratietests
- Interne netwerkpenetratietests
- Draadloze penetratietesten
- Penetratietests voor webtoepassingen
- Penetratietests voor mobiele applicaties
- API-penetratietesten
- Cloudgebaseerde penetratietesten (bijv. AWS, Azure)
- Fysieke penetratietesten
      </p>
                  <h2>
          Wat is een pentest?
      </h2>
            <p>
          Penetratietests zijn een dienst waarbij een ingehuurde ethische hacker de zwakke plekken in de beveiliging van een organisatie test om te zien hoe voorbereid ze zijn om zich te verdedigen tegen aanvallen in de echte wereld.
      </p>
                  <h2>
          Wat is een pentest bedrijf?
      </h2>
            <p>
          Een penetratietestbedrijf is een organisatie van ethische hackers die offensieve beveiligingsdiensten leveren om de beveiliging te testen tegen de dreigingen van echte aanvallen die worden gebruikt door cybercriminelen en kwaadwillenden.
      </p>
                  <h2>
          Is het legaal?
      </h2>
            <p>
            Penetratietests of ethisch hacken moeten echter door een bedrijf worden goedgekeurd om als legaal te worden beschouwd (anders wordt het als hacking beschouwd). Een goede projectscoping is belangrijk om vast te stellen wat wel en niet binnen de testgrenzen valt voordat een penetratietest wordt uitgevoerd.
      </p>
                  <h2>
          Wat kost het?
      </h2>
      <p>De kosten van een penetratietest variëren sterk, afhankelijk van het type test, bedrijfsgrootte, omvang en complexiteit, methodologie, het ervaringsniveau van penetratietesters en saneringskosten.

De gemiddelde kosten van een penetratietest kunnen variëren van € 5.000 voor kleine, niet-complexe tests tot meer dan € 100.000 voor grote, complexe projecten.</p>
      </div>

        <a href="/" class="p-5 text-xl font-medium text-yellow-500 hover:text-white">terug naar de startpagina</a>


    </div>
  </div>
</div>

app/views/nl/awspen.html.erb
<div data-tf-sidetab="vSahqHZQ" data-tf-button-color="#FBBF24" data-tf-button-text="GRATIS AFSPRAAK BOEKEN" style="all:unset;"></div><script src="//embed.typeform.com/next/embed.js"></script>




<div class="relative overflow-hidden bg-black py-16">
  <div class="hidden lg:absolute lg:inset-y-0 lg:block lg:h-full lg:w-full lg:[overflow-anchor:none]">
    <div class="relative mx-auto h-full max-w-prose text-lg" aria-hidden="true">

    </div>
  </div>
  <div class="relative px-4 sm:px-6 lg:px-8">
    <div class="mx-auto max-w-prose text-lg ">
      <h1>
        <span class="bg-white p-10 block text-center text-lg font-semibold font-Prompt text-black uppercase">Met meer dan 90 verschillende cloudhostingservices biedt de AWS-cloudomgeving mogelijkheden voor contentlevering, rekenkracht, opslag, beveiligingsbeheer, netwerkinfrastructuur en fysieke hosting. Deze services vallen doorgaans onder Infrastructure (IaaS), Platform (PaaS) of Software as a Service (SaaS). Meestal gebruikt als virtuele omgevingen voor interne organisatie en/of service aan consumenten voor gegevensopslag, code-ontwikkeling, netwerken en webtoepassingsservices.</span>
        <span class="mt-2 block text-center text-3xl font-bold leading-8 tracking-tight font-Prompt text-white uppercase sm:text-7xl">Penetratietesten van Amazon Web Services (AWS)</span>
      </h1>
      <hr>
    </div>
    <div class="mx-auto max-w-prose mx-auto mt-6 font-Prompt text-white uppercase">
      <h1>
          Wat is AWS-penetratietesten?
      </h1>
            <p>
          AWS-penetratietesten zijn rigoureuze tests van Amazon Web Services (AWS)-omgevingen om kwetsbaarheden in cyberbeveiliging bloot te leggen.

AWS-pentesten is anders dan routinematige penetratietesten. Er zijn vier belangrijke aandachtsgebieden voor AWS-penetratietests:

Uw externe AWS-cloudinfrastructuur
Uw hosting/bouwplatform-applicaties
Uw interne AWS cloud-infrastructuur
Configuratiebeoordeling van uw AWS-setup/omgeving?
      </p>
            <h1>
              Benefits of Performing a RedTeam Security AWS Penetration Test      </h1>
                  <p>
        Onze AWS-penetratietestdiensten omvatten:

Controleren op openbaar beschikbare bronnen zoals open S3-buckets.
Zoeken naar onbeveiligde AWS-inloggegevens in openbare coderepository's.
Ervoor zorgen dat beschikbare interne documentatie veilig wordt beheerd en opgeslagen in de hele omgeving.
Sinds het eerste aanbod biedt Amazon Web Services (AWS) een relatief eenvoudige en betrouwbare manier voor bedrijven om de aanschaf van extra hardware voor het hosten van hun services te verminderen. Maar met nieuwe infrastructuur en netwerkdynamiek komen onbekende risico's en aanvalspaden. Het testen van de aannames over de AWS-beveiliging van een bedrijf en de algehele cyberbeveiliging van hun cloudomgeving zijn essentiële componenten voor het handhaven van een goede beveiligingshygiëne en zijn in veel gevallen ook wettelijk verplicht.

Omdat bedreigingsactoren directe toegang hebben tot alle bronnen die aan internet zijn blootgesteld, is de barrière die ze moeten overwinnen om een ​​site aan te vallen slechts een voorbijgaande nieuwsgierigheid. Een aanvaller kan zijn tijd besteden aan het zoeken op internet naar onjuist opgeslagen AWS-toegangssleutels, API-sleutels of sessietokens om een ​​cloud-overname te proberen. Als alternatief kan een aanvaller traditionele beveiligingsproblemen van webapplicaties misbruiken om toegang te krijgen tot gevoelige AWS-infrastructuur en -rollen. Opportunistische aanvallers hebben nu veel ideale routes om binnen te dringen en zijwaarts te verplaatsen via moderne, cloudgebaseerde netwerken en webapplicaties.

Dit opent kwetsbaarheden en de mogelijke toegang tot gevoelige gegevens of gebruikersreferenties door onvoldoende beveiligde API's of fouten in code die op AWS Lambda draait. Bevoorrechte rollen en bijbehorende toegangssleutels kunnen kwaadwillenden vaak toegang geven tot functies die toegang tot een machine of het lokale netwerk ter plaatse vereisen.
      </p>
            <h1>
De Samoray-beveiligingsoplossing voor het testen van kwetsbaarheden in de AWS-beveiliging      </h1>
                  <p>
          Onze uitgebreide AWS-beveiligingstests omvatten:

Applicatiebeveiliging testen op fouten die een cloudomgeving in gevaar kunnen brengen.
Het cloudnetwerk rechtstreeks testen, of de servers nu uitsluitend intern zijn ingesteld of extern gerichte services hosten die zijn blootgesteld aan internet.
Testen op verkeerde configuraties binnen de beheerconsole van het AWS-account (inclusief een beoordeling van IAM-gebruikers, groepen, rollen, beleid en essentiële services waartoe ze mogelijk toegang hebben).
      </p>
            <p>
De penetratietests van webapplicaties omvatten het zoeken naar kwetsbaarheden in Amazon Web Services (AWS)-omgevingen en on-premises omgevingen. Bij het beoordelen van AWS-cloudbeveiliging zullen veel fundamentele technieken met betrekking tot verkenning en informatieverzameling er hetzelfde uitzien als die welke worden uitgevoerd tegen niet-cloudplatforms. Toch kunnen aanvullende instrumenten en methoden worden gebruikt om een ​​rigoureuze beoordeling van passende controles uit te voeren.

Tijdens een typische pentestopdracht kijken we bijvoorbeeld naar activa (applicaties, API's) en de ondersteunende systemen en cloudinfrastructuur waarin deze applicaties worden uitgevoerd (besturingssystemen, containers, netwerken, apparaten en servers). De methodologie voor het testen van de AWS-infrastructuur is vergelijkbaar. Naast het testen van de netwerkbeveiliging van uw cloudomgeving, analyseren we echter ook de beveiliging van configuraties die van invloed zijn op de toegang tot het AWS-account en de bijbehorende resources.

Op het meest basale niveau omvat het onderzoek van een cloudomgeving meestal het zoeken naar openbaar toegankelijke bronnen en referenties met betrekking tot AWS-services (d.w.z. S3, RDS, Lambda, EC2, CloudTrail, SG, CloudWatch) en het testen van hun informatiebeveiliging. Een meer diepgaande optie zou kunnen zijn om een ​​testgebruiker van het AWS-account in te richten en dat aan onze testers te verstrekken. Deze extra toegang zorgt voor een diepere kijk op IAM-gebruikers, groepen, rollen en beleid in de omgeving en helpt bij het zoeken naar gevaarlijke verkeerde configuraties.</p>


        <a href="/" class="p-5 text-xl font-medium text-yellow-500 hover:text-white">terug naar de startpagina</a>


    </div>
  </div>
</div>

app/views/nl/legal.html.erb
<div>
  <h1 class="font-bold text-4xl">Nl#legal</h1>
  <p>Find me in app/views/nl/legal.html.erb</p>
</div>

app/views/nl/prijs.html.erb
<div>
  <h1 class="font-bold text-4xl">Nl#prijs</h1>
  <p>Find me in app/views/nl/prijs.html.erb</p>
</div>